services:
  postgres:
    image: postgres:16
    container_name: social-pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: social_app
      POSTGRES_PASSWORD: frogchairuwu9AB
    ports:
      - "5432:5432"
    volumes:
      - social-pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U social_app -d social_network"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: social-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - social-pgadmin-data:/var/lib/pgadmin

  neo4j:
    image: neo4j:5.23-community
    container_name: social-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword123
      NEO4J_server_memory_pagecache_size: 256m
      NEO4J_server_memory_heap_initial__size: 256m
      NEO4J_server_memory_heap_max__size: 512m
      NEO4JLABS_PLUGINS: '["graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: gds.*
      NEO4J_dbms_security_procedures_allowlist: gds.*
    ports:
      - "7474:7474"   # веб-інтерфейс Neo4j Browser
      - "7687:7687"   # Bolt-протокол, яким користується neo4j-java-driver
    volumes:
      - social-neo4j-data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  social-pg-data:
  social-pgadmin-data:
  social-neo4j-data: